name: chicken20201115

on:
  schedule:
    - cron: '5 22,4 * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./airplay/requirements.txt 
        
      - name: 'chicken20201115' 
        run: python3 ./airplay/chicken.py 
        env:
            DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
            AIRPLAY_COUNT_COOKIE: ${{ secrets.AIRPLAY_COUNT_COOKIE }}
            DJJ_SEVER_JIANG: ${{ secrets.DJJ_SEVER_JIANG }}
            
            
