name: DJ_KH_Lottery

on:
  schedule:
    - cron: '15 23,3,11 * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./djj/requirements.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./djj/DJ_KH_Lottery.py
        env:
            DJJ_SHARECODE: ${{ secrets.DJJ_SHARECODE }}
            DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
            DJJ_DJJ_COOKIE: ${{ secrets.DJJ_DJJ_COOKIE }}
            DJJ_SEVER_JIANG: ${{ secrets.DJJ_SEVER_JIANG }}
            DJJ_XFJ_HEADERS: ${{ secrets.DJJ_XFJ_HEADERS }}
            
            
