name: wxmusic

on:
  schedule:
    - cron: '*/20 22,23,0,1,2 * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./music/requirements.txt 
        
      - name: 'wxmusic' 
        run: python3 ./music/wxmusic.py 
        env:
            DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
            WETCARD_YINYUE_COOKIE: ${{ secrets.WETCARD_YINYUE_COOKIE }}
            DJJ_SEVER_JIANG: ${{ secrets.DJJ_SEVER_JIANG }}
            
            
